public class AutoGeneratedFieldProperties : System.Web.UI.IStateManager
{

	// Constructors
	public AutoGeneratedFieldProperties() {}

	// Methods
	public Type GetType() {}
	public virtual string ToString() {}
	public virtual bool Equals(object obj) {}
	public virtual int GetHashCode() {}

	// Properties
	public string DataField { get{} set{} }
	public bool IsReadOnly { get{} set{} }
	public string Name { get{} set{} }
	public Type Type { get{} set{} }
}

