public class AutoGeneratedField : BoundField, System.Web.UI.IStateManager, System.Web.UI.IDataSourceViewSchemaAccessor
{

	// Constructors
	public AutoGeneratedField(string dataField) {}

	// Methods
	public virtual void ExtractValuesFromCell(System.Collections.Specialized.IOrderedDictionary dictionary, DataControlFieldCell cell, DataControlRowState rowState, bool includeReadOnly) {}
	public virtual void ValidateSupportsCallback() {}
	public virtual bool Initialize(bool enableSorting, System.Web.UI.Control control) {}
	public virtual void InitializeCell(DataControlFieldCell cell, DataControlCellType cellType, DataControlRowState rowState, int rowIndex) {}
	public virtual string ToString() {}
	public Type GetType() {}
	public virtual bool Equals(object obj) {}
	public virtual int GetHashCode() {}

	// Properties
	public string DataFormatString { get{} set{} }
	public Type DataType { get{} set{} }
	public bool InsertVisible { get{} set{} }
	public bool ConvertEmptyStringToNull { get{} set{} }
	public bool ApplyFormatInEditMode { get{} set{} }
	public string DataField { get{} set{} }
	public string HeaderText { get{} set{} }
	public bool HtmlEncode { get{} set{} }
	public bool HtmlEncodeFormatString { get{} set{} }
	public string NullDisplayText { get{} set{} }
	public bool ReadOnly { get{} set{} }
	public string AccessibleHeaderText { get{} set{} }
	public Style ControlStyle { get{} }
	public TableItemStyle FooterStyle { get{} }
	public string FooterText { get{} set{} }
	public string HeaderImageUrl { get{} set{} }
	public TableItemStyle HeaderStyle { get{} }
	public TableItemStyle ItemStyle { get{} }
	public bool ShowHeader { get{} set{} }
	public string SortExpression { get{} set{} }
	public bool Visible { get{} set{} }
}

