public class Brushes
{

	// Methods
	public Type GetType() {}
	public virtual string ToString() {}
	public virtual bool Equals(object obj) {}
	public virtual int GetHashCode() {}

	// Properties
	public Brush Transparent { get{} }
	public Brush AliceBlue { get{} }
	public Brush AntiqueWhite { get{} }
	public Brush Aqua { get{} }
	public Brush Aquamarine { get{} }
	public Brush Azure { get{} }
	public Brush Beige { get{} }
	public Brush Bisque { get{} }
	public Brush Black { get{} }
	public Brush BlanchedAlmond { get{} }
	public Brush Blue { get{} }
	public Brush BlueViolet { get{} }
	public Brush Brown { get{} }
	public Brush BurlyWood { get{} }
	public Brush CadetBlue { get{} }
	public Brush Chartreuse { get{} }
	public Brush Chocolate { get{} }
	public Brush Coral { get{} }
	public Brush CornflowerBlue { get{} }
	public Brush Cornsilk { get{} }
	public Brush Crimson { get{} }
	public Brush Cyan { get{} }
	public Brush DarkBlue { get{} }
	public Brush DarkCyan { get{} }
	public Brush DarkGoldenrod { get{} }
	public Brush DarkGray { get{} }
	public Brush DarkGreen { get{} }
	public Brush DarkKhaki { get{} }
	public Brush DarkMagenta { get{} }
	public Brush DarkOliveGreen { get{} }
	public Brush DarkOrange { get{} }
	public Brush DarkOrchid { get{} }
	public Brush DarkRed { get{} }
	public Brush DarkSalmon { get{} }
	public Brush DarkSeaGreen { get{} }
	public Brush DarkSlateBlue { get{} }
	public Brush DarkSlateGray { get{} }
	public Brush DarkTurquoise { get{} }
	public Brush DarkViolet { get{} }
	public Brush DeepPink { get{} }
	public Brush DeepSkyBlue { get{} }
	public Brush DimGray { get{} }
	public Brush DodgerBlue { get{} }
	public Brush Firebrick { get{} }
	public Brush FloralWhite { get{} }
	public Brush ForestGreen { get{} }
	public Brush Fuchsia { get{} }
	public Brush Gainsboro { get{} }
	public Brush GhostWhite { get{} }
	public Brush Gold { get{} }
	public Brush Goldenrod { get{} }
	public Brush Gray { get{} }
	public Brush Green { get{} }
	public Brush GreenYellow { get{} }
	public Brush Honeydew { get{} }
	public Brush HotPink { get{} }
	public Brush IndianRed { get{} }
	public Brush Indigo { get{} }
	public Brush Ivory { get{} }
	public Brush Khaki { get{} }
	public Brush Lavender { get{} }
	public Brush LavenderBlush { get{} }
	public Brush LawnGreen { get{} }
	public Brush LemonChiffon { get{} }
	public Brush LightBlue { get{} }
	public Brush LightCoral { get{} }
	public Brush LightCyan { get{} }
	public Brush LightGoldenrodYellow { get{} }
	public Brush LightGreen { get{} }
	public Brush LightGray { get{} }
	public Brush LightPink { get{} }
	public Brush LightSalmon { get{} }
	public Brush LightSeaGreen { get{} }
	public Brush LightSkyBlue { get{} }
	public Brush LightSlateGray { get{} }
	public Brush LightSteelBlue { get{} }
	public Brush LightYellow { get{} }
	public Brush Lime { get{} }
	public Brush LimeGreen { get{} }
	public Brush Linen { get{} }
	public Brush Magenta { get{} }
	public Brush Maroon { get{} }
	public Brush MediumAquamarine { get{} }
	public Brush MediumBlue { get{} }
	public Brush MediumOrchid { get{} }
	public Brush MediumPurple { get{} }
	public Brush MediumSeaGreen { get{} }
	public Brush MediumSlateBlue { get{} }
	public Brush MediumSpringGreen { get{} }
	public Brush MediumTurquoise { get{} }
	public Brush MediumVioletRed { get{} }
	public Brush MidnightBlue { get{} }
	public Brush MintCream { get{} }
	public Brush MistyRose { get{} }
	public Brush Moccasin { get{} }
	public Brush NavajoWhite { get{} }
	public Brush Navy { get{} }
	public Brush OldLace { get{} }
	public Brush Olive { get{} }
	public Brush OliveDrab { get{} }
	public Brush Orange { get{} }
	public Brush OrangeRed { get{} }
	public Brush Orchid { get{} }
	public Brush PaleGoldenrod { get{} }
	public Brush PaleGreen { get{} }
	public Brush PaleTurquoise { get{} }
	public Brush PaleVioletRed { get{} }
	public Brush PapayaWhip { get{} }
	public Brush PeachPuff { get{} }
	public Brush Peru { get{} }
	public Brush Pink { get{} }
	public Brush Plum { get{} }
	public Brush PowderBlue { get{} }
	public Brush Purple { get{} }
	public Brush Red { get{} }
	public Brush RosyBrown { get{} }
	public Brush RoyalBlue { get{} }
	public Brush SaddleBrown { get{} }
	public Brush Salmon { get{} }
	public Brush SandyBrown { get{} }
	public Brush SeaGreen { get{} }
	public Brush SeaShell { get{} }
	public Brush Sienna { get{} }
	public Brush Silver { get{} }
	public Brush SkyBlue { get{} }
	public Brush SlateBlue { get{} }
	public Brush SlateGray { get{} }
	public Brush Snow { get{} }
	public Brush SpringGreen { get{} }
	public Brush SteelBlue { get{} }
	public Brush Tan { get{} }
	public Brush Teal { get{} }
	public Brush Thistle { get{} }
	public Brush Tomato { get{} }
	public Brush Turquoise { get{} }
	public Brush Violet { get{} }
	public Brush Wheat { get{} }
	public Brush White { get{} }
	public Brush WhiteSmoke { get{} }
	public Brush Yellow { get{} }
	public Brush YellowGreen { get{} }
}

