public class Pens
{

	// Methods
	public Type GetType() {}
	public virtual string ToString() {}
	public virtual bool Equals(object obj) {}
	public virtual int GetHashCode() {}

	// Properties
	public Pen Transparent { get{} }
	public Pen AliceBlue { get{} }
	public Pen AntiqueWhite { get{} }
	public Pen Aqua { get{} }
	public Pen Aquamarine { get{} }
	public Pen Azure { get{} }
	public Pen Beige { get{} }
	public Pen Bisque { get{} }
	public Pen Black { get{} }
	public Pen BlanchedAlmond { get{} }
	public Pen Blue { get{} }
	public Pen BlueViolet { get{} }
	public Pen Brown { get{} }
	public Pen BurlyWood { get{} }
	public Pen CadetBlue { get{} }
	public Pen Chartreuse { get{} }
	public Pen Chocolate { get{} }
	public Pen Coral { get{} }
	public Pen CornflowerBlue { get{} }
	public Pen Cornsilk { get{} }
	public Pen Crimson { get{} }
	public Pen Cyan { get{} }
	public Pen DarkBlue { get{} }
	public Pen DarkCyan { get{} }
	public Pen DarkGoldenrod { get{} }
	public Pen DarkGray { get{} }
	public Pen DarkGreen { get{} }
	public Pen DarkKhaki { get{} }
	public Pen DarkMagenta { get{} }
	public Pen DarkOliveGreen { get{} }
	public Pen DarkOrange { get{} }
	public Pen DarkOrchid { get{} }
	public Pen DarkRed { get{} }
	public Pen DarkSalmon { get{} }
	public Pen DarkSeaGreen { get{} }
	public Pen DarkSlateBlue { get{} }
	public Pen DarkSlateGray { get{} }
	public Pen DarkTurquoise { get{} }
	public Pen DarkViolet { get{} }
	public Pen DeepPink { get{} }
	public Pen DeepSkyBlue { get{} }
	public Pen DimGray { get{} }
	public Pen DodgerBlue { get{} }
	public Pen Firebrick { get{} }
	public Pen FloralWhite { get{} }
	public Pen ForestGreen { get{} }
	public Pen Fuchsia { get{} }
	public Pen Gainsboro { get{} }
	public Pen GhostWhite { get{} }
	public Pen Gold { get{} }
	public Pen Goldenrod { get{} }
	public Pen Gray { get{} }
	public Pen Green { get{} }
	public Pen GreenYellow { get{} }
	public Pen Honeydew { get{} }
	public Pen HotPink { get{} }
	public Pen IndianRed { get{} }
	public Pen Indigo { get{} }
	public Pen Ivory { get{} }
	public Pen Khaki { get{} }
	public Pen Lavender { get{} }
	public Pen LavenderBlush { get{} }
	public Pen LawnGreen { get{} }
	public Pen LemonChiffon { get{} }
	public Pen LightBlue { get{} }
	public Pen LightCoral { get{} }
	public Pen LightCyan { get{} }
	public Pen LightGoldenrodYellow { get{} }
	public Pen LightGreen { get{} }
	public Pen LightGray { get{} }
	public Pen LightPink { get{} }
	public Pen LightSalmon { get{} }
	public Pen LightSeaGreen { get{} }
	public Pen LightSkyBlue { get{} }
	public Pen LightSlateGray { get{} }
	public Pen LightSteelBlue { get{} }
	public Pen LightYellow { get{} }
	public Pen Lime { get{} }
	public Pen LimeGreen { get{} }
	public Pen Linen { get{} }
	public Pen Magenta { get{} }
	public Pen Maroon { get{} }
	public Pen MediumAquamarine { get{} }
	public Pen MediumBlue { get{} }
	public Pen MediumOrchid { get{} }
	public Pen MediumPurple { get{} }
	public Pen MediumSeaGreen { get{} }
	public Pen MediumSlateBlue { get{} }
	public Pen MediumSpringGreen { get{} }
	public Pen MediumTurquoise { get{} }
	public Pen MediumVioletRed { get{} }
	public Pen MidnightBlue { get{} }
	public Pen MintCream { get{} }
	public Pen MistyRose { get{} }
	public Pen Moccasin { get{} }
	public Pen NavajoWhite { get{} }
	public Pen Navy { get{} }
	public Pen OldLace { get{} }
	public Pen Olive { get{} }
	public Pen OliveDrab { get{} }
	public Pen Orange { get{} }
	public Pen OrangeRed { get{} }
	public Pen Orchid { get{} }
	public Pen PaleGoldenrod { get{} }
	public Pen PaleGreen { get{} }
	public Pen PaleTurquoise { get{} }
	public Pen PaleVioletRed { get{} }
	public Pen PapayaWhip { get{} }
	public Pen PeachPuff { get{} }
	public Pen Peru { get{} }
	public Pen Pink { get{} }
	public Pen Plum { get{} }
	public Pen PowderBlue { get{} }
	public Pen Purple { get{} }
	public Pen Red { get{} }
	public Pen RosyBrown { get{} }
	public Pen RoyalBlue { get{} }
	public Pen SaddleBrown { get{} }
	public Pen Salmon { get{} }
	public Pen SandyBrown { get{} }
	public Pen SeaGreen { get{} }
	public Pen SeaShell { get{} }
	public Pen Sienna { get{} }
	public Pen Silver { get{} }
	public Pen SkyBlue { get{} }
	public Pen SlateBlue { get{} }
	public Pen SlateGray { get{} }
	public Pen Snow { get{} }
	public Pen SpringGreen { get{} }
	public Pen SteelBlue { get{} }
	public Pen Tan { get{} }
	public Pen Teal { get{} }
	public Pen Thistle { get{} }
	public Pen Tomato { get{} }
	public Pen Turquoise { get{} }
	public Pen Violet { get{} }
	public Pen Wheat { get{} }
	public Pen White { get{} }
	public Pen WhiteSmoke { get{} }
	public Pen Yellow { get{} }
	public Pen YellowGreen { get{} }
}

