public interface DHTMLStyleElementEvents2
{

	// Methods
	public abstract virtual void onerror(IHTMLEventObj evtObj) {}
	public abstract virtual bool onhelp(IHTMLEventObj evtObj) {}
	public abstract virtual bool onclick(IHTMLEventObj evtObj) {}
	public abstract virtual bool ondblclick(IHTMLEventObj evtObj) {}
	public abstract virtual bool onkeypress(IHTMLEventObj evtObj) {}
	public abstract virtual void onkeydown(IHTMLEventObj evtObj) {}
	public abstract virtual void onkeyup(IHTMLEventObj evtObj) {}
	public abstract virtual void onmouseout(IHTMLEventObj evtObj) {}
	public abstract virtual void onmouseover(IHTMLEventObj evtObj) {}
	public abstract virtual void onmousemove(IHTMLEventObj evtObj) {}
	public abstract virtual void onmousedown(IHTMLEventObj evtObj) {}
	public abstract virtual void onmouseup(IHTMLEventObj evtObj) {}
	public abstract virtual bool onselectstart(IHTMLEventObj evtObj) {}
	public abstract virtual void onfilterchange(IHTMLEventObj evtObj) {}
	public abstract virtual bool ondragstart(IHTMLEventObj evtObj) {}
	public abstract virtual bool onbeforeupdate(IHTMLEventObj evtObj) {}
	public abstract virtual void onafterupdate(IHTMLEventObj evtObj) {}
	public abstract virtual bool onerrorupdate(IHTMLEventObj evtObj) {}
	public abstract virtual bool onrowexit(IHTMLEventObj evtObj) {}
	public abstract virtual void onrowenter(IHTMLEventObj evtObj) {}
	public abstract virtual void ondatasetchanged(IHTMLEventObj evtObj) {}
	public abstract virtual void ondataavailable(IHTMLEventObj evtObj) {}
	public abstract virtual void ondatasetcomplete(IHTMLEventObj evtObj) {}
	public abstract virtual void onlosecapture(IHTMLEventObj evtObj) {}
	public abstract virtual void onpropertychange(IHTMLEventObj evtObj) {}
	public abstract virtual void onscroll(IHTMLEventObj evtObj) {}
	public abstract virtual void onfocus(IHTMLEventObj evtObj) {}
	public abstract virtual void onblur(IHTMLEventObj evtObj) {}
	public abstract virtual void onresize(IHTMLEventObj evtObj) {}
	public abstract virtual bool ondrag(IHTMLEventObj evtObj) {}
	public abstract virtual void ondragend(IHTMLEventObj evtObj) {}
	public abstract virtual bool ondragenter(IHTMLEventObj evtObj) {}
	public abstract virtual bool ondragover(IHTMLEventObj evtObj) {}
	public abstract virtual void ondragleave(IHTMLEventObj evtObj) {}
	public abstract virtual bool ondrop(IHTMLEventObj evtObj) {}
	public abstract virtual bool onbeforecut(IHTMLEventObj evtObj) {}
	public abstract virtual bool oncut(IHTMLEventObj evtObj) {}
	public abstract virtual bool onbeforecopy(IHTMLEventObj evtObj) {}
	public abstract virtual bool oncopy(IHTMLEventObj evtObj) {}
	public abstract virtual bool onbeforepaste(IHTMLEventObj evtObj) {}
	public abstract virtual bool onpaste(IHTMLEventObj evtObj) {}
	public abstract virtual bool oncontextmenu(IHTMLEventObj evtObj) {}
	public abstract virtual void onrowsdelete(IHTMLEventObj evtObj) {}
	public abstract virtual void onrowsinserted(IHTMLEventObj evtObj) {}
	public abstract virtual void oncellchange(IHTMLEventObj evtObj) {}
	public abstract virtual void onreadystatechange(IHTMLEventObj evtObj) {}
	public abstract virtual void onlayoutcomplete(IHTMLEventObj evtObj) {}
	public abstract virtual void onpage(IHTMLEventObj evtObj) {}
	public abstract virtual void onmouseenter(IHTMLEventObj evtObj) {}
	public abstract virtual void onmouseleave(IHTMLEventObj evtObj) {}
	public abstract virtual void onactivate(IHTMLEventObj evtObj) {}
	public abstract virtual void ondeactivate(IHTMLEventObj evtObj) {}
	public abstract virtual bool onbeforedeactivate(IHTMLEventObj evtObj) {}
	public abstract virtual bool onbeforeactivate(IHTMLEventObj evtObj) {}
	public abstract virtual void onfocusin(IHTMLEventObj evtObj) {}
	public abstract virtual void onfocusout(IHTMLEventObj evtObj) {}
	public abstract virtual void onmove(IHTMLEventObj evtObj) {}
	public abstract virtual bool oncontrolselect(IHTMLEventObj evtObj) {}
	public abstract virtual bool onmovestart(IHTMLEventObj evtObj) {}
	public abstract virtual void onmoveend(IHTMLEventObj evtObj) {}
	public abstract virtual bool onresizestart(IHTMLEventObj evtObj) {}
	public abstract virtual void onresizeend(IHTMLEventObj evtObj) {}
	public abstract virtual bool onmousewheel(IHTMLEventObj evtObj) {}
	public abstract virtual void onload(IHTMLEventObj evtObj) {}
}

